
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_DONE = "GET_PRODUCT_DONE";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const POST_PRODUCT_REQUEST = "POST_PRODUCT_REQUEST";
export const POST_PRODUCT_DONE = "POST_PRODUCT_DONE";
export const POST_PRODUCT_FAIL = "POST_PRODUCT_FAIL";

